url: ""
baseurl: ""

# Site settings
title: Pseudocode
email: hi@pseudocode.agency
description: "(for Google search results) and in your feed.xml site description."


tech:
- name: JavaScript
  pic: 1
  details: Angular.js, Vue.js, Backbone.js
- name: C#
  pic: 2
  details: ASP.NET MVC
- name: SQL
  pic: 3
  details: MS SQL Server
- name: SharePoint
  pic: 4
  details: SharePoint
  
# Build settings
markdown: kramdown
permalink: pretty
